In [1]:
import pandas as pd
import numpy as np
import requests

In [2]:
import pandas as pd
import numpy as np
import os, sys

PROJECT_ROOT = os.path.join(os.getcwd(), '..',)#os.path.dirname(os.path.dirname(__file__))
sys.path.insert(1, PROJECT_ROOT) 
from prepare_data import ExchangeData

class BinanceLoader(ExchangeData):

    def __init__(self, exchange, symbol_type):
        super().__init__(exchange, symbol_type)


    def get_ts13(self, datetime:str, timezone:str='Asia/Taipei'):
        ts13 = int(pd.to_datetime(datetime).tz_localize(timezone).timestamp()*1000)
        return ts13
  
    
    def fetch_ohlcv(self, url, symbol, start_ts13, freq, limit, columns, need_col=["datetime", "open", "high", "low", "close", "volume"]):
        """
        Mind
        - timezone = 'UTC'
        - spot: https://binance-docs.github.io/apidocs/spot/en/#kline-candlestick-data
        - usd: https://binance-docs.github.io/apidocs/futures/en/#kline-candlestick-data
        - coin: https://binance-docs.github.io/apidocs/delivery/en/#kline-candlestick-data
        """

        params = {
            'symbol': symbol, 
            'interval': freq, 
            'startTime': start_ts13, 
            'limit':limit,
        }

        data = requests.get(url, params=params).json()
        df = pd.DataFrame(data, columns=columns)
        df['datetime'] = pd.to_datetime(df['open_time'], unit='ms')
        
        return df[need_col].set_index(['datetime'])

In [3]:
bl = BinanceLoader(exchange='binance', symbol_type='usd')
# binance_loader.get_limit_kline()
# binance_loader.get_columns_kline()

In [4]:
df = bl.fetch_ohlcv(
    url = bl.get_end_point() + bl.get_suffix_kline(),
    symbol = 'BTCUSDT',
    start_ts13 = bl.get_ts13('2024-1-11'),
    freq = '1m',
    limit = bl.get_limit_kline(),
    columns = bl.get_columns_kline(),
)

In [ ]:
fetch_ohlcv(self, url, symbol, start_ts13, freq, limit, columns, need_col=["datetime", "open", "high", "low", "close", "volume"]):

In [ ]:
def download_ohlcv(self, start:str, freq:str, symbol_li:list=None,):
    """
    Download ohlcv for the given symbols.

    Args:
    - start (str): Start date. (e.g., '2023-1-1 12:00:00+08:00')
    - freq (str): Frequency of data (e.g., '30m', '1d', '1h'). 
    - spot_li (list): List of symbols to download.
    - limit (int): Limit of data points to fetch.

    Example:
        download_spot_ohlcv('2023-1-1 12:00:00+08:00', '30m', ['BTCUSDT', 'ETHUSDT'])

    Mind
    - No symbol checking in symbol_li.
    - max_limit = 1000 for spot markets
    - timezone = 'UTC'
    """
    save_dir = os.path.join(os.path.dirname(__file__), 'data_base', self.exchange, self.symbol_type, freq)
    os.makedirs(save_dir, exist_ok=True)

    if not symbol_li:
        url_exchange_info = self.get_end_point() + self.get_suffix_exchange_info()
        exchange_info = requests.get(url_exchange_info).json()
        symbol_li = [i['symbol'] for i in exchange_info['symbols'] if i['quoteAsset']=='USDT']

    for symbol in symbol_li:
        symbol_amount = len(symbol_li)
        print(f"downloading {symbol_li.index(symbol)+1}/{symbol_amount}")

        df = self.fetch_ohlcv()



        df = self.fetch_spot_ohlcv(symbol, start, freq, limit)
        df['datetime'] = pd.to_datetime(df['datetime'], unit='ms').dt.tz_localize('UTC').dt.tz_convert(self.timezone)
        df = df.set_index(['datetime', 'code']).sort_index()

        file_name = f"{symbol}_ohlcv.pkl"
        file_path = os.path.join(save_dir, file_name)
        df.to_pickle(file_path)


        suffix = '/api/v3/exchangeInfo'
        url = self.end_point + suffix

        response = requests.get(url)
        exchange_info = response.json()
        
        spot_li = [i['symbol'] for i in exchange_info['symbols'] if i['quoteAsset']=='USDT']

    for symbol in spot_li:
        symbol_amount = len(spot_li)
        print(f"downloading {spot_li.index(symbol)+1}/{symbol_amount}")

        df = self.fetch_spot_ohlcv(symbol, start, freq, limit)
        df['datetime'] = pd.to_datetime(df['datetime'], unit='ms').dt.tz_localize('UTC').dt.tz_convert(self.timezone)
        df = df.set_index(['datetime', 'code']).sort_index()

        file_name = f"{symbol}_ohlcv.pkl"
        file_path = os.path.join(save_dir, file_name)
        df.to_pickle(file_path)

        print(f"{symbol} has been downloaded to {file_path}")

In [20]:
def fetch_spot_ohlcv(self, symbol, start, freq, limit=1000):
    """
    Mind
    - max_limit = 1000 for spot markets
    - timezone = 'UTC'
    """
    ohlcv_list = []
    start_ts13 = self.spot_client.parse8601(start)
    columns = ['datetime', 'open', 'high', 'low', 'close', 'volume']

    while True:
        ohlcv = self.spot_client.fetch_ohlcv(symbol, freq, since=start_ts13, limit=limit)
        ohlcv_list.extend(ohlcv)
        print(f"fetching {symbol} from {pd.to_datetime(start_ts13, unit='ms').tz_localize('UTC')}")
        if len(ohlcv) < limit:
            break    
        start_ts13 = ohlcv[-1][0]

    df = pd.DataFrame(ohlcv_list, columns=columns)
    df['code'] = symbol

    return df

IndentationError: unexpected indent (183207436.py, line 43)

In [ ]:
url = 'https://fapi.binance.com/fapi/v1/klines'
symbol = 'BTCUSDT'
interval = '1h'
start = (int(pd.to_datetime('2024-1-16').tz_localize('UTC').timestamp()*1000))
end = (int(pd.to_datetime('2024-1-17').tz_localize('UTC').timestamp()*1000))

par = {'symbol': symbol, 'interval': interval, 'startTime': start, 'limit':1500}
result = requests.get(url, params= par)

data = result.json()
df = pd.DataFrame(data, columns=['timestamp', 'open', 'high', 'low', 'close', 'volume', 'close_time', 'quote_asset_volume', 'number_of_trades', 'taker_buy_base_asset_volume', 'taker_buy_quote_asset_volume', 'ignore'])

# Convert timestamp to datetime
df['timestamp'] = pd.to_datetime(df['timestamp'], unit='ms')
df['close_time'] = pd.to_datetime(df['close_time'], unit='ms')

In [ ]:
df

,timestamp,open,high,low,close,volume,close_time,quote_asset_volume,number_of_trades,taker_buy_base_asset_volume,taker_buy_quote_asset_volume,ignore
0,2024-01-16 00:00:00,42515.00,42679.00,42466.10,42604.70,4807.989,2024-01-16 00:59:59.999,204815547.27400,83161,2569.204,109445671.41200,0
1,2024-01-16 01:00:00,42604.60,42733.70,42556.60,42591.70,4728.842,2024-01-16 01:59:59.999,201602869.51377,77287,2468.202,105223777.86928,0
2,2024-01-16 02:00:00,42591.70,42732.80,42552.00,42702.10,5519.024,2024-01-16 02:59:59.999,235440131.60158,76101,3005.014,128184200.59768,0
3,2024-01-16 03:00:00,42702.10,42942.00,42695.70,42919.50,7032.131,2024-01-16 03:59:59.999,301186807.16910,95191,3731.711,159828199.19971,0
4,2024-01-16 04:00:00,42919.30,42945.00,42759.90,42805.20,5516.792,2024-01-16 04:59:59.999,236430231.24909,79812,2404.169,103019924.01450,0
...,...,...,...,...,...,...,...,...,...,...,...,...
148,2024-01-22 04:00:00,41199.50,41221.90,40755.50,40776.70,16886.142,2024-01-22 04:59:59.999,691938324.84133,197795,7244.088,296892497.02860,0
149,2024-01-22 05:00:00,40776.80,41153.70,40666.00,41133.60,16571.740,2024-01-22 05:59:59.999,678119430.09441,216322,9030.073,369521591.69400,0
150,2024-01-22 06:00:00,41133.60,41334.90,41002.00,41201.30,10932.641,2024-01-22 06:59:59.999,450049507.40093,140795,5694.183,234457663.32660,0
151,2024-01-22 07:00:00,41201.40,41210.30,40971.30,41042.60,6855.448,2024-01-22 07:59:59.999,281680490.23046,93563,2894.699,118953235.99750,0
152,2024-01-22 08:00:00,41042.70,41044.60,40828.50,40904.70,7935.631,2024-01-22 08:59:59.999,324792097.30793,97584,3633.526,148718971.56241,0

In [ ]:
def fetch_ohlcv()

    par = {'symbol': symbol, 'interval': interval, 'startTime': start, 'endTime': end, 'limit':1500}
    result = requests.get(url, params= par)

    data = result.json()
    df = pd.DataFrame(data, columns=['timestamp', 'open', 'high', 'low', 'close', 'volume', 'close_time', 'quote_asset_volume', 'number_of_trades', 'taker_buy_base_asset_volume', 'taker_buy_quote_asset_volume', 'ignore'])

    # Convert timestamp to datetime
    df['timestamp'] = pd.to_datetime(df['timestamp'], unit='ms')
    df['close_time'] = pd.to_datetime(df['close_time'], unit='ms')

In [ ]:
start = '2024-1-16'

ohlcv_list = []
start_ts13 = (int(pd.to_datetime(start).tz_localize('UTC').timestamp()*1000))
columns = ['timestamp', 'open', 'high', 'low', 'close', 'volume', 'close_time', 'quote_asset_volume', 'number_of_trades', 'taker_buy_base_asset_volume', 'taker_buy_quote_asset_volume', 'ignore']

symbol = ['']

while True:
    ohlcv = fetch_ohlcv(symbol, freq, since=start_ts13, limit=limit)
    ohlcv_list.extend(ohlcv)
    print(f"fetching {symbol} from {pd.to_datetime(start_ts13, unit='ms').tz_localize('UTC')}")
    if len(ohlcv) < limit:
        break    
    start_ts13 = ohlcv[-1][0]

df = pd.DataFrame(ohlcv_list, columns=columns)
df['code'] = symbol

In [ ]:
    def fetch_spot_ohlcv(self, symbol, start, freq, limit=1000):
        """
        Mind
        - max_limit = 1000 for spot markets
        - timezone = 'UTC'
        """
        ohlcv_list = []
        start_ts13 = self.spot_client.parse8601(start)
        columns = ['datetime', 'open', 'high', 'low', 'close', 'volume']

        while True:
            ohlcv = self.spot_client.fetch_ohlcv(symbol, freq, since=start_ts13, limit=limit)
            ohlcv_list.extend(ohlcv)
            print(f"fetching {symbol} from {pd.to_datetime(start_ts13, unit='ms').tz_localize('UTC')}")
            if len(ohlcv) < limit:
                break    
            start_ts13 = ohlcv[-1][0]

        df = pd.DataFrame(ohlcv_list, columns=columns)
        df['code'] = symbol

        return df

In [ ]:
df

,timestamp,open,high,low,close,volume,close_time,quote_asset_volume,number_of_trades,taker_buy_base_asset_volume,taker_buy_quote_asset_volume,ignore
0,2024-01-15 16:00:00,42278.70,42321.70,42270.00,42293.90,195.416,2024-01-15 16:00:59.999,8265298.55050,2628,99.421,4205229.86100,0
1,2024-01-15 16:01:00,42293.90,42325.20,42249.10,42325.10,306.457,2024-01-15 16:01:59.999,12957396.44980,3671,132.720,5612473.52310,0
2,2024-01-15 16:02:00,42325.10,42329.00,42315.60,42326.00,141.747,2024-01-15 16:02:59.999,5999378.99640,2320,91.166,3858624.49430,0
3,2024-01-15 16:03:00,42325.90,42329.00,42312.70,42329.00,112.064,2024-01-15 16:03:59.999,4742941.73040,1497,41.884,1772775.89250,0
4,2024-01-15 16:04:00,42328.90,42329.00,42306.20,42317.30,118.162,2024-01-15 16:04:59.999,5000608.16390,1767,71.139,3010551.34960,0
...,...,...,...,...,...,...,...,...,...,...,...,...
1495,2024-01-16 16:55:00,43223.30,43240.00,43191.10,43219.10,241.874,2024-01-16 16:55:59.999,10452382.17970,3232,77.441,3346566.98800,0
1496,2024-01-16 16:56:00,43219.00,43228.40,43188.00,43228.40,197.886,2024-01-16 16:56:59.999,8550386.59120,3121,113.102,4887004.80280,0
1497,2024-01-16 16:57:00,43228.40,43230.70,43190.00,43198.00,171.405,2024-01-16 16:57:59.999,7406332.77420,2907,54.102,2337457.31980,0
1498,2024-01-16 16:58:00,43198.10,43233.00,43198.10,43233.00,141.865,2024-01-16 16:58:59.999,6130617.98470,2076,94.103,4066084.44950,0
1499,2024-01-16 16:59:00,43233.00,43249.90,43202.00,43249.80,104.763,2024-01-16 16:59:59.999,4529401.98060,2003,50.449,2181142.99790,0

In [ ]:
df

,timestamp,open,high,low,close,volume,close_time,quote_asset_volume,number_of_trades,taker_buy_base_asset_volume,taker_buy_quote_asset_volume,ignore
0,2024-01-16 00:00:00,42515.00,42679.00,42466.10,42604.70,4807.989,2024-01-16 00:59:59.999,204815547.27400,83161,2569.204,109445671.41200,0
1,2024-01-16 01:00:00,42604.60,42733.70,42556.60,42591.70,4728.842,2024-01-16 01:59:59.999,201602869.51377,77287,2468.202,105223777.86928,0
2,2024-01-16 02:00:00,42591.70,42732.80,42552.00,42702.10,5519.024,2024-01-16 02:59:59.999,235440131.60158,76101,3005.014,128184200.59768,0
3,2024-01-16 03:00:00,42702.10,42942.00,42695.70,42919.50,7032.131,2024-01-16 03:59:59.999,301186807.16910,95191,3731.711,159828199.19971,0
4,2024-01-16 04:00:00,42919.30,42945.00,42759.90,42805.20,5516.792,2024-01-16 04:59:59.999,236430231.24909,79812,2404.169,103019924.01450,0
5,2024-01-16 05:00:00,42805.20,42932.50,42759.00,42765.30,4148.775,2024-01-16 05:59:59.999,177768542.06161,62002,1804.142,77303801.58932,0
6,2024-01-16 06:00:00,42765.40,42779.10,42648.30,42744.40,5399.943,2024-01-16 06:59:59.999,230675732.23206,70080,2603.802,111232031.19860,0
7,2024-01-16 07:00:00,42744.50,42788.10,42600.50,42788.10,4965.136,2024-01-16 07:59:59.999,211981558.81910,72742,2339.181,99875735.40810,0
8,2024-01-16 08:00:00,42788.50,43029.70,42718.80,43021.50,8975.581,2024-01-16 08:59:59.999,385057362.00039,116370,4709.810,202042156.26929,0
9,2024-01-16 09:00:00,43021.50,43164.90,42899.60,42937.00,12361.569,2024-01-16 09:59:59.999,531854604.09884,154271,5766.724,248161235.10286,0
10,2024-01-16 10:00:00,42937.10,42969.10,42850.10,42870.00,4996.402,2024-01-16 10:59:59.999,214330401.70252,77222,2272.043,97458941.15610,0
11,2024-01-16 11:00:00,42870.00,42944.00,42753.60,42894.90,5799.531,2024-01-16 11:59:59.999,248477812.40573,89069,2783.509,119267557.93200,0
12,2024-01-16 12:00:00,42894.60,43170.00,42854.70,43160.10,10657.016,2024-01-16 12:59:59.999,458687025.43086,140800,5690.128,244883556.95346,0
13,2024-01-16 13:00:00,43160.10,43181.70,42705.60,42805.70,13452.139,2024-01-16 13:59:59.999,577738820.42607,178130,5875.156,252316047.06842,0
14,2024-01-16 14:00:00,42805.60,42954.90,42050.00,42700.10,55063.011,2024-01-16 14:59:59.999,2339032327.49285,482930,27369.832,1162700571.73088,0
15,2024-01-16 15:00:00,42700.10,43333.00,42545.60,43251.70,42560.654,2024-01-16 15:59:59.999,1829727779.22117,467564,22371.241,961932288.64958,0
16,2024-01-16 16:00:00,43251.00,43450.00,43003.20,43249.80,24381.082,2024-01-16 16:59:59.999,1053561168.61729,303949,11984.811,518026116.95023,0
17,2024-01-16 17:00:00,43249.80,43249.80,43027.60,43051.40,8896.750,2024-01-16 17:59:59.999,383592787.07708,141618,4100.675,176804597.93600,0
18,2024-01-16 18:00:00,43051.40,43159.90,42825.50,43008.80,10532.470,2024-01-16 18:59:59.999,452704978.73674,150400,4989.955,214532323.40028,0
19,2024-01-16 19:00:00,43008.80,43182.30,42940.80,43164.80,6539.237,2024-01-16 19:59:59.999,281851089.52688,111119,3419.993,147409607.13358,0
20,2024-01-16 20:00:00,43164.80,43376.20,43061.70,43195.90,13191.003,2024-01-16 20:59:59.999,570091882.08342,176733,6423.255,277617491.46230,0
21,2024-01-16 21:00:00,43195.90,43589.00,43181.60,43427.50,14845.850,2024-01-16 21:59:59.999,644702392.97803,210535,7763.609,337149931.64552,0
22,2024-01-16 22:00:00,43427.40,43499.20,43200.00,43208.60,6772.759,2024-01-16 22:59:59.999,293456284.43150,96668,3024.883,131070464.38490,0
23,2024-01-16 23:00:00,43208.60,43285.00,43105.20,43133.00,6063.547,2024-01-16 23:59:59.999,261851294.08512,78159,3025.786,130676635.87790,0
24,2024-01-17 00:00:00,43133.00,43174.00,43044.30,43089.40,4724.355,2024-01-17 00:59:59.999,203603498.44426,78279,2383.035,102701481.35380,0
25,2024-01-17 01:00:00,43089.50,43198.00,42953.00,42965.40,6154.108,2024-01-17 01:59:59.999,265134376.05658,89394,2812.743,121229107.77120,0
26,2024-01-17 02:00:00,42965.40,43062.60,42910.50,42995.10,4909.457,2024-01-17 02:59:59.999,211078214.99966,76768,2303.442,99045782.88746,0
27,2024-01-17 03:00:00,42995.20,43029.80,42838.80,42842.10,4813.284,2024-01-17 03:59:59.999,206641713.26688,72352,2193.563,94184085.31110,0
28,2024-01-17 04:00:00,42842.00,42920.10,42770.90,42848.30,6443.281,2024-01-17 04:59:59.999,276046545.26483,85413,3394.937,145461160.78800,0
29,2024-01-17 05:00:00,42848.20,42933.00,42754.50,42778.50,4240.183,2024-01-17 05:59:59.999,181670460.07071,68630,2132.798,91388315.04502,0
30,2024-01-17 06:00:00,42778.60,42875.30,42760.00,42801.50,3740.640,2024-01-17 06:59:59.999,160186536.75050,63585,1846.271,79063520.15250,0
31,2024-01-17 07:00:00,42801.50,42849.10,42616.00,42654.00,10124.856,2024-01-17 07:59:59.999,432630599.33488,120511,4639.431,198251011.74310,0
32,2024-01-17 08:00:00,42654.00,42750.00,42555.80,42725.60,7421.221,2024-01-17 08:59:59.999,316657771.80067,112941,4121.083,175851437.88428,0
33,2024-01-17 09:00:00,42725.50,42830.00,42666.40,42677.00,5570.268,2024-01-17 09:59:59.999,238256937.21907,78084,2863.564,122496682.01019,0
34,2024-01-17 10:00:00,42676.90,42855.80,42614.40,42854.00,6951.373,2024-01-17 10:59:59.999,297109287.80279,98557,3915.038,167350615.77519,0
35,2024-01-17 11:00:00,42854.00,42854.00,42670.00,42681.00,5188.435,2024-01-17 11:59:59.999,221815103.00778,83642,2380.247,101762613.89220,0
36,2024-01-17 12:00:00,42681.00,42795.00,42355.50,42785.20,15118.043,2024-01-17 12:59:59.999,644378738.74785,195400,7539.166,321493791.37965,0
37,2024-01-17 13:00:00,42785.20,42786.60,42500.00,42610.40,8473.725,2024-01-17 13:59:59.999,361297534.04509,136093,3953.923,168603211.82890,0
38,2024-01-17 14:00:00,42610.40,42934.90,42360.00,42576.20,28182.670,2024-01-17 14:59:59.999,1201224647.89281,318559,14019.593,597629737.82707,0
39,2024-01-17 15:00:00,42576.10,42774.20,42457.50,42478.30,17076.067,2024-01-17 15:59:59.999,727517553.00389,219009,8381.548,357152867.53808,0
40,2024-01-17 16:00:00,42478.20,42565.40,42263.10,42358.50,14317.307,2024-01-17 16:59:59.999,607072028.51824,205887,7219.625,306192633.66210,0
41,2024-01-17 17:00:00,42358.50,42472.30,42200.00,42375.40,9867.665,2024-01-17 17:59:59.999,417888002.67146,146074,5088.218,215531409.79676,0
42,2024-01-17 18:00:00,42375.50,42622.00,42272.50,42616.00,9442.580,2024-01-17 18:59:59.999,400944083.13564,133978,4913.354,208675317.77544,0
43,2024-01-17 19:00:00,42616.10,42757.60,42555.90,42617.50,7244.545,2024-01-17 19:59:59.999,308954554.12586,107832,3906.875,166629095.62886,0
44,2024-01-17 20:00:00,42617.60,42869.30,42560.00,42722.00,12998.782,2024-01-17 20:59:59.999,555220202.72238,167735,5862.934,250444795.76081,0
45,2024-01-17 21:00:00,42722.10,42825.50,42606.00,42685.70,5518.498,2024-01-17 21:59:59.999,235731427.79367,85034,2950.535,126037017.17269,0
46,2024-01-17 22:00:00,42685.70,42740.40,42444.00,42727.00,5410.299,2024-01-17 22:59:59.999,230525161.80279,85129,2704.685,115271175.30417,0
47,2024-01-17 23:00:00,42727.10,42794.30,42622.40,42783.40,5464.439,2024-01-17 23:59:59.999,233445030.71820,67511,2853.992,121923759.41040,0

In [ ]:
result

In [ ]:
url = 'https://api.binance.com/api/v3/klines'
symbol = 'BTCUSDT'
interval = '1h'
start = (int(dt.datetime(2024,1,16).timestamp()*1000))
end = (int(dt.datetime(2024,1,17).timestamp()*1000))
par = {'symbol': symbol, 'interval': interval, 'startTime': start, 'endTime': end}
data = pd.DataFrame(json.loads(requests.get(url, params= par).text))
#format columns name
data.columns = ['datetime', 'open', 'high', 'low', 'close', 'volume','close_time', 'qav', 'num_trades','taker_base_vol', 'taker_quote_vol', 'ignore']
data.index = [dt.datetime.fromtimestamp(x/1000.0) for x in data.datetime]
data=data.astype(float)

In [ ]:
data

,datetime,open,high,low,close,volume,close_time,qav,num_trades,taker_base_vol,taker_quote_vol,ignore
2024-01-16 00:00:00,1.705334e+12,42278.99,42549.00,42249.00,42522.61,1121.26001,1.705338e+12,4.755025e+07,57874.0,627.94266,2.663062e+07,0.0
2024-01-16 01:00:00,1.705338e+12,42522.60,42779.78,42521.10,42696.58,1280.44041,1.705342e+12,5.463545e+07,60358.0,621.15357,2.650563e+07,0.0
2024-01-16 02:00:00,1.705342e+12,42696.57,43400.43,42696.57,43015.82,7891.28853,1.705345e+12,3.407552e+08,302218.0,3496.84512,1.508873e+08,0.0
2024-01-16 03:00:00,1.705345e+12,43015.82,43133.80,42825.84,42992.67,2038.31756,1.705349e+12,8.763074e+07,84396.0,996.74754,4.285295e+07,0.0
2024-01-16 04:00:00,1.705349e+12,42992.67,43114.45,42850.00,42960.00,1245.90158,1.705352e+12,5.357909e+07,51410.0,589.07810,2.533819e+07,0.0
2024-01-16 05:00:00,1.705352e+12,42959.99,42960.00,42710.00,42716.00,920.68651,1.705356e+12,3.942414e+07,42115.0,446.01729,1.909922e+07,0.0
2024-01-16 06:00:00,1.705356e+12,42716.00,42818.31,42342.18,42628.00,1850.23943,1.705360e+12,7.877147e+07,77507.0,872.71986,3.715815e+07,0.0
2024-01-16 07:00:00,1.705360e+12,42628.00,42639.99,42474.00,42511.10,1301.68577,1.705363e+12,5.539559e+07,52454.0,633.27021,2.695090e+07,0.0
2024-01-16 08:00:00,1.705363e+12,42511.10,42674.00,42466.88,42600.00,1007.25697,1.705367e+12,4.290120e+07,45056.0,549.01107,2.338284e+07,0.0
2024-01-16 09:00:00,1.705367e+12,42600.01,42726.97,42555.00,42584.34,875.50468,1.705370e+12,3.732198e+07,51073.0,481.01387,2.050440e+07,0.0
2024-01-16 10:00:00,1.705370e+12,42584.34,42732.45,42553.96,42710.00,967.07632,1.705374e+12,4.125672e+07,40061.0,570.86601,2.435330e+07,0.0
2024-01-16 11:00:00,1.705374e+12,42710.00,42939.50,42702.00,42924.56,1175.44142,1.705378e+12,5.032283e+07,63720.0,693.49291,2.968863e+07,0.0
2024-01-16 12:00:00,1.705378e+12,42924.57,42946.05,42755.33,42803.19,917.47192,1.705381e+12,3.931332e+07,43590.0,413.89934,1.773479e+07,0.0
2024-01-16 13:00:00,1.705381e+12,42803.18,42931.33,42768.00,42773.82,814.04215,1.705385e+12,3.488871e+07,46095.0,404.56730,1.733932e+07,0.0
2024-01-16 14:00:00,1.705385e+12,42773.82,42780.00,42646.89,42741.09,963.99198,1.705388e+12,4.117681e+07,38711.0,438.44566,1.872730e+07,0.0
2024-01-16 15:00:00,1.705388e+12,42741.10,42791.14,42606.92,42791.13,952.74344,1.705392e+12,4.069503e+07,36211.0,572.83028,2.447009e+07,0.0
2024-01-16 16:00:00,1.705392e+12,42791.14,43022.00,42720.06,43014.53,1421.99021,1.705396e+12,6.097431e+07,50474.0,798.66090,3.424611e+07,0.0
2024-01-16 17:00:00,1.705396e+12,43014.53,43153.66,42896.41,42940.01,1762.34779,1.705399e+12,7.580862e+07,78104.0,879.49396,3.783698e+07,0.0
2024-01-16 18:00:00,1.705399e+12,42940.01,42971.10,42851.45,42872.00,823.26434,1.705403e+12,3.531541e+07,42455.0,400.11847,1.716293e+07,0.0
2024-01-16 19:00:00,1.705403e+12,42872.01,42945.54,42753.55,42900.54,841.64338,1.705406e+12,3.606910e+07,43344.0,439.78097,1.884845e+07,0.0
2024-01-16 20:00:00,1.705406e+12,42900.55,43166.00,42857.32,43156.12,1134.71946,1.705410e+12,4.882684e+07,63187.0,650.78086,2.800459e+07,0.0
2024-01-16 21:00:00,1.705410e+12,43156.11,43174.48,42700.00,42805.83,1752.96929,1.705414e+12,7.529723e+07,71479.0,850.64330,3.654063e+07,0.0
2024-01-16 22:00:00,1.705414e+12,42805.83,42954.00,42050.00,42690.00,9514.26629,1.705417e+12,4.036346e+08,214623.0,5617.32261,2.381443e+08,0.0
2024-01-16 23:00:00,1.705417e+12,42690.00,43314.73,42543.01,43252.67,5566.03085,1.705421e+12,2.391977e+08,199971.0,3028.30284,1.301385e+08,0.0
2024-01-17 00:00:00,1.705421e+12,43252.45,43434.00,43011.10,43249.72,3535.61086,1.705424e+12,1.527714e+08,138098.0,1807.11275,7.808829e+07,0.0

In [ ]:
requests.get?

Signature: requests.get(url, params=None, **kwargs)
Docstring:
Sends a GET request.

:param url: URL for the new :class:`Request` object.
:param params: (optional) Dictionary, list of tuples or bytes to send
    in the query string for the :class:`Request`.
:param \*\*kwargs: Optional arguments that ``request`` takes.
:return: :class:`Response <Response>` object
:rtype: requests.Response
File:      c:\users\hottari\anaconda3\envs\env3.9\lib\site-packages\requests\api.py
Type:      function

In [ ]:
start = int(pd.to_datetime('2024-1-16').timestamp()*1000)
end = int(pd.to_datetime('2024-1-17').timestamp()*1000)

In [ ]:
suffix = '/fapi/v1/klines'
url = end_point + suffix
params = {
    'symbol': 'BTCUSDT',
    'interval': '1T',
    'startTime': start, 
    'endTime': end,
    'limit': 1500
}

In [ ]:
response = requests.get(
    url, 
    params = params
)
#result = response.json()

In [ ]:
response.text

'<html>\r\n<head><title>404 Not Found</title></head>\r\n<body>\r\n<center><h1>404 Not Found</h1></center>\r\n<hr><center>nginx</center>\r\n</body>\r\n</html>\r\n'

In [ ]:
requests.get?

Signature: requests.get(url, params=None, **kwargs)
Docstring:
Sends a GET request.

:param url: URL for the new :class:`Request` object.
:param params: (optional) Dictionary, list of tuples or bytes to send
    in the query string for the :class:`Request`.
:param \*\*kwargs: Optional arguments that ``request`` takes.
:return: :class:`Response <Response>` object
:rtype: requests.Response
File:      c:\users\hottari\anaconda3\envs\env3.9\lib\site-packages\requests\api.py
Type:      function

In [ ]:
response