In [ ]:
"""
max_limit = 1000 for spot markets
"timezone":"UTC"

"""

In [1]:
import pandas as pd
import numpy as np
import requests

import os, sys
import ccxt

In [2]:
api_url = "https://api.binance.com/api/v3/exchangeInfo"

response = requests.get(api_url)
exchange_info = response.json()

spot_li = [i['symbol'] for i in exchange_info['symbols'] if i['quoteAsset']=='USDT']

In [3]:
sys.path.insert(1, f"{os.getcwd()}/../../../Lab3310/Systematic-Sherpa")
from data_handler.binance_handler import BinanceHandler

In [4]:
handler = BinanceHandler()

In [5]:
handler.binance_handler_init('SPOT', '1m', 'select')

Getting data: 2023-12-01 00:00:00, BTCUSDT, 1m
[BTCUSDT] Fetched data from - 1701360000000 - 2023-12-01 00:00:00 to 2023-12-01 16:39:00
[BTCUSDT] Fetched data from - 1701420000000 - 2023-12-01 16:40:00 to 2023-12-02 09:19:00
[BTCUSDT] Fetched data from - 1701480000000 - 2023-12-02 09:20:00 to 2023-12-03 01:59:00
[BTCUSDT] Fetched data from - 1701540000000 - 2023-12-03 02:00:00 to 2023-12-03 18:39:00
[BTCUSDT] Fetched data from - 1701600000000 - 2023-12-03 18:40:00 to 2023-12-04 11:19:00
[BTCUSDT] Fetched data from - 1701660000000 - 2023-12-04 11:20:00 to 2023-12-05 03:59:00
[BTCUSDT] Fetched data from - 1701720000000 - 2023-12-05 04:00:00 to 2023-12-05 20:39:00
[BTCUSDT] Fetched data from - 1701780000000 - 2023-12-05 20:40:00 to 2023-12-06 13:19:00
[BTCUSDT] Fetched data from - 1701840000000 - 2023-12-06 13:20:00 to 2023-12-07 05:59:00
[BTCUSDT] Fetched data from - 1701900000000 - 2023-12-07 06:00:00 to 2023-12-07 22:39:00
[BTCUSDT] Fetched data from - 1701960000000 - 2023-12-07 22:40:00 to 2023-12-08 15:19:00
[BTCUSDT] Fetched data from - 1702020000000 - 2023-12-08 15:20:00 to 2023-12-09 07:59:00
[BTCUSDT] Fetched data from - 1702080000000 - 2023-12-09 08:00:00 to 2023-12-10 00:39:00
[BTCUSDT] Fetched data from - 1702140000000 - 2023-12-10 00:40:00 to 2023-12-10 17:19:00
[BTCUSDT] Fetched data from - 1702200000000 - 2023-12-10 17:20:00 to 2023-12-11 09:59:00
[BTCUSDT] Fetched data from - 1702260000000 - 2023-12-11 10:00:00 to 2023-12-12 02:39:00
[BTCUSDT] Fetched data from - 1702320000000 - 2023-12-12 02:40:00 to 2023-12-12 19:19:00
[BTCUSDT] Fetched data from - 1702380000000 - 2023-12-12 19:20:00 to 2023-12-13 11:59:00
[BTCUSDT] Fetched data from - 1702440000000 - 2023-12-13 12:00:00 to 2023-12-14 04:39:00
[BTCUSDT] Fetched data from - 1702500000000 - 2023-12-14 04:40:00 to 2023-12-14 21:19:00
[BTCUSDT] Fetched data from - 1702560000000 - 2023-12-14 21:20:00 to 2023-12-15 13:59:00
[BTCUSDT] Fetched data from - 1702620000000 - 2023-12-15 14:00:00 to 2023-12-16 06:39:00
[BTCUSDT] Fetched data from - 1702680000000 - 2023-12-16 06:40:00 to 2023-12-16 23:19:00
[BTCUSDT] Fetched data from - 1702740000000 - 2023-12-16 23:20:00 to 2023-12-17 15:59:00
[BTCUSDT] Fetched data from - 1702800000000 - 2023-12-17 16:00:00 to 2023-12-18 08:39:00
[BTCUSDT] Fetched data from - 1702860000000 - 2023-12-18 08:40:00 to 2023-12-19 01:19:00
[BTCUSDT] Fetched data from - 1702920000000 - 2023-12-19 01:20:00 to 2023-12-19 17:59:00
[BTCUSDT] Fetched data from - 1702980000000 - 2023-12-19 18:00:00 to 2023-12-20 10:39:00
[BTCUSDT] Fetched data from - 1703040000000 - 2023-12-20 10:40:00 to 2023-12-21 03:19:00
[BTCUSDT] Fetched data from - 1703100000000 - 2023-12-21 03:20:00 to 2023-12-21 19:59:00
[BTCUSDT] Fetched data from - 1703160000000 - 2023-12-21 20:00:00 to 2023-12-22 12:28:00
Acquired # of timepoints: 30989
First data point: [1701360000000, 37619.85, 37619.85, 37586.25, 37587.42, 39.09593]
Last data point: [1703219280000, 44066.81, 44066.82, 44062.14, 44062.15, 2.69041]
Saved data.

In [30]:
df_ = pd.read_csv(r'C:\Users\a1222\Lab3310\Systematic-Sherpa\data_base\BINANCE\SPOT\1m\BTCUSDT_SPOT_1m.csv')
df_['datetime'] = pd.to_datetime(df_['datetime']).dt.tz_localize('Asia/Taipei').dt.tz_convert('UTC')

In [33]:
df_.set_index('datetime')['2023-12-1':].reset_index()

,datetime,open,high,low,close,volume
0,2023-12-01 00:00:00+00:00,37723.97,37744.72,37722.73,37738.91,34.53633
1,2023-12-01 00:01:00+00:00,37738.91,37738.91,37723.72,37723.72,12.71120
2,2023-12-01 00:02:00+00:00,37723.72,37723.73,37699.57,37699.57,33.22694
3,2023-12-01 00:03:00+00:00,37699.58,37699.58,37699.57,37699.57,6.89939
4,2023-12-01 00:04:00+00:00,37699.57,37699.58,37688.27,37688.35,14.22495
...,...,...,...,...,...,...
30503,2023-12-22 04:23:00+00:00,44045.36,44053.07,44045.02,44045.03,20.21157
30504,2023-12-22 04:24:00+00:00,44045.02,44045.24,44045.02,44045.24,26.62383
30505,2023-12-22 04:25:00+00:00,44045.24,44077.86,44045.23,44069.94,27.70364
30506,2023-12-22 04:26:00+00:00,44069.95,44079.65,44061.10,44074.01,18.59401
30507,2023-12-22 04:27:00+00:00,44074.01,44074.01,44062.00,44066.82,12.53198

In [21]:
df_all

,,open,high,low,close,volume
date,code,,,,,
2023-12-01 00:00:00+00:00,BTCUSDT,37723.97,37744.72,37722.73,37738.91,34.53633
2023-12-01 00:01:00+00:00,BTCUSDT,37738.91,37738.91,37723.72,37723.72,12.71120
2023-12-01 00:02:00+00:00,BTCUSDT,37723.72,37723.73,37699.57,37699.57,33.22694
2023-12-01 00:03:00+00:00,BTCUSDT,37699.58,37699.58,37699.57,37699.57,6.89939
2023-12-01 00:04:00+00:00,BTCUSDT,37699.57,37699.58,37688.27,37688.35,14.22495
...,...,...,...,...,...,...
2023-12-22 04:24:00+00:00,BTCUSDT,44045.02,44045.24,44045.02,44045.24,26.62383
2023-12-22 04:25:00+00:00,BTCUSDT,44045.24,44077.86,44045.23,44069.94,27.70364
2023-12-22 04:26:00+00:00,BTCUSDT,44069.95,44079.65,44061.10,44074.01,18.59401
2023-12-22 04:27:00+00:00,BTCUSDT,44074.01,44074.01,44062.00,44066.82,12.53198
2023-12-22 04:28:00+00:00,BTCUSDT,44066.81,44066.82,44062.14,44062.15,4.44588

In [6]:
def fetch_ohlcv_data(exchange, symbol, start, freq, limit=1000):
    ohlcv_list = []
    from_ts = exchange.parse8601(start)

    columns = ['date', 'open', 'high', 'low', 'close', 'volume']

    while True:
        ohlcv = exchange.fetch_ohlcv(symbol, freq, since=from_ts, limit=limit)
        ohlcv_list.extend(ohlcv)
        
        if len(ohlcv) < limit:
            break
        
        from_ts = ohlcv[-1][0]

    df = pd.DataFrame(ohlcv_list, columns=columns)
    df['code'] = symbol
    #df['date'] = pd.to_datetime(df['date'], unit='ms').dt.tz_localize('UTC')

    return df

def fetch_all_ohlcv_data(exchange, symbol_list, freq, start):
    df_li = [fetch_ohlcv_data(exchange, symbol, start, freq).set_index(['date', 'code']) for symbol in symbol_list]
    df_all = pd.concat(df_li, axis='rows').reset_index()
    df_all['date'] = pd.to_datetime(df_all['date'], unit='ms').dt.tz_localize('UTC')
    df_all = df_all.set_index(['date', 'code']).sort_index()
    
    return df_all

In [7]:
binance = ccxt.binance()
freq = '1m'
start = '2023-12-01 00:00:00'
symbol_list = ['BTCUSDT']
df_all = fetch_all_ohlcv_data(binance, symbol_list, freq, start)

In [8]:
df_all

,,open,high,low,close,volume
date,code,,,,,
2023-12-01 00:00:00+00:00,BTCUSDT,37723.97,37744.72,37722.73,37738.91,34.53633
2023-12-01 00:01:00+00:00,BTCUSDT,37738.91,37738.91,37723.72,37723.72,12.71120
2023-12-01 00:02:00+00:00,BTCUSDT,37723.72,37723.73,37699.57,37699.57,33.22694
2023-12-01 00:03:00+00:00,BTCUSDT,37699.58,37699.58,37699.57,37699.57,6.89939
2023-12-01 00:04:00+00:00,BTCUSDT,37699.57,37699.58,37688.27,37688.35,14.22495
...,...,...,...,...,...,...
2023-12-22 04:24:00+00:00,BTCUSDT,44045.02,44045.24,44045.02,44045.24,26.62383
2023-12-22 04:25:00+00:00,BTCUSDT,44045.24,44077.86,44045.23,44069.94,27.70364
2023-12-22 04:26:00+00:00,BTCUSDT,44069.95,44079.65,44061.10,44074.01,18.59401
2023-12-22 04:27:00+00:00,BTCUSDT,44074.01,44074.01,44062.00,44066.82,12.53198
2023-12-22 04:28:00+00:00,BTCUSDT,44066.81,44066.82,44062.14,44062.15,4.44588

In [11]:
ex = ccxt.binance()
from_ts = ex.parse8601('2023-12-01 00:00:00')
ohlcv_list = []

symbol = 'BTCUSDT'
freq = '1m'
columns = ['date', 'open', 'high', 'low', 'close', 'volume']
ohlcv = ex.fetch_ohlcv(symbol, freq, since=from_ts, limit=1000)
ohlcv_list.append(ohlcv)
while True:
    from_ts = ohlcv[-1][0]
    new_ohlcv = ex.fetch_ohlcv(symbol, freq, since=from_ts, limit=1000)
    ohlcv.extend(new_ohlcv)
    if len(new_ohlcv)!=1000:
    	break

df = pd.DataFrame(ohlcv, columns=columns)
df['date'] = pd.to_datetime(df['date'], unit='ms').dt.tz_localize('UTC')
df['Code'] = symbol

In [34]:
new_ohlcv

[[1703187000000, 43471.09, 43493.9, 43462.0, 43492.08, 20.92466],
 [1703187060000, 43492.07, 43518.25, 43486.11, 43517.99, 15.34516],
 [1703187120000, 43518.0, 43544.2, 43505.43, 43521.1, 34.87255],
 [1703187180000, 43521.1, 43530.0, 43496.0, 43512.36, 15.97069],
 [1703187240000, 43512.36, 43530.63, 43510.18, 43530.63, 10.53373],
 [1703187300000, 43530.63, 43530.63, 43466.96, 43470.75, 22.841],
 [1703187360000, 43470.76, 43478.28, 43445.3, 43454.39, 24.23682],
 [1703187420000, 43454.4, 43454.89, 43422.85, 43422.85, 26.48789],
 [1703187480000, 43422.85, 43443.99, 43411.1, 43443.98, 23.80702],
 [1703187540000, 43443.99, 43457.24, 43423.68, 43457.23, 23.38478],
 [1703187600000, 43457.23, 43482.18, 43456.0, 43481.99, 15.0014],
 [1703187660000, 43481.99, 43482.02, 43476.9, 43478.0, 9.26048],
 [1703187720000, 43478.01, 43479.08, 43441.1, 43446.0, 14.9279],
 [1703187780000, 43445.99, 43459.32, 43445.99, 43454.39, 9.1492],
 [1703187840000, 43454.39, 43484.0, 43454.39, 43483.99, 4.92547],
 [1703187900000, 43484.0, 43498.0, 43461.1, 43465.81, 11.70817],
 [1703187960000, 43465.82, 43476.0, 43459.44, 43467.99, 14.21551],
 [1703188020000, 43467.99, 43493.9, 43448.0, 43481.11, 23.15478],
 [1703188080000, 43481.11, 43486.0, 43458.6, 43460.76, 18.34739],
 [1703188140000, 43460.76, 43493.38, 43460.76, 43493.38, 14.92999],
 [1703188200000, 43493.38, 43510.0, 43493.37, 43509.99, 22.16402],
 [1703188260000, 43509.99, 43510.0, 43473.63, 43479.6, 25.23938],
 [1703188320000, 43479.61, 43510.0, 43478.17, 43509.99, 13.71783],
 [1703188380000, 43509.99, 43510.0, 43506.46, 43506.46, 11.54501],
 [1703188440000, 43506.47, 43600.0, 43506.46, 43586.85, 64.45611],
 [1703188500000, 43586.86, 43599.78, 43551.84, 43551.87, 52.1737],
 [1703188560000, 43551.87, 43563.08, 43529.0, 43541.09, 28.95497],
 [1703188620000, 43541.1, 43546.81, 43520.82, 43546.81, 18.74461],
 [1703188680000, 43546.8, 43576.16, 43543.82, 43575.13, 15.28769],
 [1703188740000, 43575.13, 43592.78, 43572.71, 43588.8, 11.36196],
 [1703188800000, 43588.79, 43597.77, 43554.01, 43597.76, 26.62156],
 [1703188860000, 43597.77, 43614.48, 43584.64, 43614.48, 18.88241],
 [1703188920000, 43614.48, 43627.99, 43603.57, 43603.57, 23.37596],
 [1703188980000, 43603.58, 43609.4, 43591.81, 43609.4, 15.81022],
 [1703189040000, 43609.39, 43612.26, 43594.0, 43598.07, 8.76239],
 [1703189100000, 43598.06, 43615.68, 43589.84, 43596.01, 16.77393],
 [1703189160000, 43596.01, 43601.68, 43584.0, 43590.28, 10.77318],
 [1703189220000, 43590.28, 43636.36, 43590.28, 43636.35, 18.03868],
 [1703189280000, 43636.36, 43636.36, 43601.1, 43617.62, 17.79743],
 [1703189340000, 43617.62, 43667.8, 43617.61, 43659.43, 22.43283],
 [1703189400000, 43659.42, 43659.43, 43628.0, 43629.46, 15.07931],
 [1703189460000, 43629.46, 43651.1, 43625.76, 43627.11, 12.7171],
 [1703189520000, 43627.12, 43640.35, 43620.0, 43640.35, 15.1399],
 [1703189580000, 43640.34, 43656.56, 43636.33, 43641.22, 10.00019],
 [1703189640000, 43641.21, 43669.94, 43641.12, 43665.6, 24.91641],
 [1703189700000, 43665.61, 43667.99, 43648.1, 43648.1, 27.172],
 [1703189760000, 43648.11, 43657.99, 43610.99, 43639.91, 21.11906],
 [1703189820000, 43639.9, 43650.96, 43639.9, 43650.96, 12.55806],
 [1703189880000, 43650.95, 43663.73, 43639.1, 43661.66, 24.7883],
 [1703189940000, 43661.65, 43663.41, 43651.59, 43661.6, 10.19119],
 [1703190000000, 43661.6, 43661.61, 43651.6, 43657.71, 8.54073],
 [1703190060000, 43657.7, 43657.71, 43612.76, 43612.76, 13.76169],
 [1703190120000, 43612.77, 43654.58, 43612.76, 43651.81, 15.7264],
 [1703190180000, 43651.8, 43657.71, 43632.48, 43652.98, 11.97334],
 [1703190240000, 43652.97, 43675.48, 43652.97, 43675.48, 8.08177],
 [1703190300000, 43675.47, 43681.1, 43652.97, 43679.65, 27.96799],
 [1703190360000, 43679.65, 43714.48, 43651.58, 43651.59, 23.70884],
 [1703190420000, 43651.59, 43687.92, 43646.0, 43687.92, 23.85885],
 [1703190480000, 43687.91, 43700.78, 43675.9, 43688.64, 11.99776],
 [1703190540000, 43688.64, 43704.71, 43687.21, 43704.71, 13.93182],
 [1703190600000, 43704.7, 43723.14, 43698.99, 43722.53, 20.42321],
 [1703190660000, 43721.69, 43741.1, 43712.85, 43740.83, 18.40096],
 [1703190720000, 43740.83, 43745.9, 43731.1, 43743.29, 18.43085],
 [1703190780000, 43743.29, 43750.89, 43711.1, 43720.09, 28.0066],
 [1703190840000, 43720.1, 43720.1, 43687.22, 43687.22, 19.18083],
 [1703190900000, 43687.22, 43718.67, 43681.1, 43718.66, 17.65674],
 [1703190960000, 43718.67, 43722.59, 43694.0, 43711.09, 12.08988],
 [1703191020000, 43711.09, 43722.55, 43694.0, 43697.42, 23.80336],
 [1703191080000, 43697.41, 43697.42, 43662.12, 43662.13, 16.45856],
 [1703191140000, 43662.12, 43667.76, 43662.12, 43667.76, 7.93757],
 [1703191200000, 43667.76, 43705.61, 43662.13, 43697.15, 17.19844],
 [1703191260000, 43697.15, 43699.54, 43668.16, 43687.99, 11.78026],
 [1703191320000, 43688.0, 43697.16, 43666.28, 43666.29, 19.50403],
 [1703191380000, 43666.28, 43675.22, 43659.3, 43674.0, 13.85201],
 [1703191440000, 43674.51, 43720.95, 43674.0, 43719.63, 16.9003],
 [1703191500000, 43719.63, 43748.91, 43719.62, 43748.91, 30.5823],
 [1703191560000, 43748.9, 43775.0, 43748.9, 43768.95, 25.22406],
 [1703191620000, 43768.95, 43771.6, 43731.77, 43731.77, 87.89802],
 [1703191680000, 43731.77, 43746.0, 43718.89, 43723.37, 26.08018],
 [1703191740000, 43723.37, 43723.37, 43707.19, 43707.2, 13.81816],
 [1703191800000, 43707.19, 43717.99, 43707.15, 43708.91, 19.69918],
 [1703191860000, 43708.92, 43724.77, 43708.91, 43720.79, 11.0211],
 [1703191920000, 43720.8, 43745.6, 43720.79, 43741.1, 45.87262],
 [1703191980000, 43741.1, 43770.28, 43741.09, 43766.6, 26.58461],
 [1703192040000, 43766.6, 43766.6, 43728.47, 43748.75, 29.8269],
 [1703192100000, 43748.76, 43748.76, 43727.96, 43734.11, 17.98686],
 [1703192160000, 43734.11, 43769.39, 43734.11, 43769.38, 7.73261],
 [1703192220000, 43769.38, 43771.59, 43762.3, 43763.53, 22.79684],
 [1703192280000, 43763.52, 43764.0, 43751.1, 43764.0, 14.61006],
 [1703192340000, 43763.99, 43796.8, 43755.21, 43796.8, 35.58403],
 [1703192400000, 43796.8, 43796.8, 43734.11, 43734.11, 19.68415],
 [1703192460000, 43734.11, 43758.87, 43734.11, 43747.37, 18.19377],
 [1703192520000, 43747.38, 43747.38, 43733.0, 43733.01, 14.54102],
 [1703192580000, 43733.0, 43735.3, 43719.77, 43731.51, 9.93065],
 [1703192640000, 43731.5, 43750.43, 43726.56, 43750.43, 26.27713],
 [1703192700000, 43750.43, 43761.1, 43734.47, 43734.48, 19.05354],
 [1703192760000, 43734.48, 43784.73, 43734.47, 43761.81, 18.03636],
 [1703192820000, 43761.81, 43777.3, 43752.7, 43752.7, 13.41754],
 [1703192880000, 43752.7, 43767.22, 43747.14, 43767.22, 16.20385],
 [1703192940000, 43767.21, 43775.48, 43757.02, 43771.09, 10.43215],
 [1703193000000, 43771.09, 43771.1, 43757.03, 43760.35, 13.15596],
 [1703193060000, 43760.34, 43760.35, 43748.11, 43748.12, 12.42759],
 [1703193120000, 43748.12, 43759.72, 43734.47, 43752.6, 28.3881],
 [1703193180000, 43752.59, 43765.34, 43752.59, 43760.41, 9.15027],
 [1703193240000, 43760.4, 43780.0, 43760.4, 43779.99, 49.97312],
 [1703193300000, 43780.0, 43780.0, 43750.54, 43771.1, 19.1182],
 [1703193360000, 43771.1, 43807.2, 43771.09, 43793.15, 29.54037],
 [1703193420000, 43793.15, 43793.16, 43774.44, 43782.02, 10.78374],
 [1703193480000, 43782.02, 43793.16, 43782.01, 43793.15, 6.43108],
 [1703193540000, 43793.15, 43793.16, 43775.03, 43780.65, 17.04225],
 [1703193600000, 43780.64, 43793.19, 43780.64, 43793.19, 9.50294],
 [1703193660000, 43793.18, 43793.19, 43744.54, 43755.45, 16.08187],
 [1703193720000, 43755.45, 43755.45, 43744.54, 43750.63, 12.25807],
 [1703193780000, 43750.63, 43775.49, 43750.63, 43775.48, 10.4432],
 [1703193840000, 43775.49, 43775.49, 43775.48, 43775.48, 2.07518],
 [1703193900000, 43775.49, 43775.49, 43765.68, 43765.68, 4.98426],
 [1703193960000, 43765.68, 43771.38, 43761.26, 43761.26, 6.99594],
 [1703194020000, 43761.26, 43770.0, 43728.08, 43747.55, 38.10612],
 [1703194080000, 43747.56, 43761.1, 43747.55, 43761.1, 11.69842],
 [1703194140000, 43761.09, 43773.92, 43761.09, 43773.91, 13.65036],
 [1703194200000, 43773.91, 43773.92, 43771.83, 43773.9, 5.01791],
 [1703194260000, 43773.91, 43805.78, 43773.9, 43805.78, 13.94381],
 [1703194320000, 43805.77, 43818.82, 43787.94, 43787.94, 35.4083],
 [1703194380000, 43787.95, 43820.16, 43787.94, 43820.16, 13.01421],
 [1703194440000, 43820.16, 43826.23, 43801.1, 43822.66, 22.89015],
 [1703194500000, 43822.66, 43846.15, 43822.66, 43837.09, 27.71136],
 [1703194560000, 43837.09, 43846.13, 43824.42, 43846.12, 24.19535],
 [1703194620000, 43846.13, 43920.0, 43841.0, 43888.25, 64.76851],
 [1703194680000, 43888.24, 43990.0, 43888.24, 43975.8, 72.56246],
 [1703194740000, 43975.8, 44005.51, 43965.33, 43978.33, 90.1596],
 [1703194800000, 43978.33, 43978.33, 43934.08, 43934.09, 33.49822],
 [1703194860000, 43934.08, 44001.1, 43924.24, 43999.47, 46.57845],
 [1703194920000, 43999.46, 44040.0, 43975.67, 44025.98, 62.12616],
 [1703194980000, 44025.99, 44030.0, 43977.27, 44030.0, 30.98574],
 [1703195040000, 44029.99, 44030.0, 43991.1, 44012.86, 39.30924],
 [1703195100000, 44012.87, 44048.29, 43991.1, 44048.28, 45.11794],
 [1703195160000, 44048.28, 44119.2, 44048.28, 44093.01, 96.37489],
 [1703195220000, 44093.0, 44119.2, 44081.99, 44105.07, 53.42414],
 [1703195280000, 44105.08, 44119.2, 44068.5, 44081.09, 30.425],
 [1703195340000, 44081.09, 44085.44, 44062.78, 44071.54, 28.92926],
 [1703195400000, 44071.54, 44071.54, 44010.14, 44025.55, 36.39221],
 [1703195460000, 44025.56, 44034.35, 44006.28, 44006.29, 28.66694],
 [1703195520000, 44006.29, 44047.18, 43991.05, 44006.63, 44.0395],
 [1703195580000, 44006.62, 44014.68, 43983.27, 43987.7, 17.73199],
 [1703195640000, 43987.7, 43989.91, 43962.46, 43962.47, 17.62816],
 [1703195700000, 43962.47, 43991.1, 43961.9, 43977.88, 42.61348],
 [1703195760000, 43977.89, 43977.89, 43961.1, 43970.73, 23.77669],
 [1703195820000, 43970.74, 43996.89, 43968.25, 43973.09, 19.25137],
 [1703195880000, 43973.08, 44005.36, 43973.08, 43992.31, 18.4442],
 [1703195940000, 43992.32, 43998.34, 43983.59, 43994.93, 18.53521],
 [1703196000000, 43994.93, 44013.0, 43943.8, 43943.8, 37.81779],
 [1703196060000, 43943.81, 43943.81, 43900.0, 43915.61, 20.37138],
 [1703196120000, 43915.62, 43931.09, 43901.31, 43901.32, 17.23539],
 [1703196180000, 43901.31, 43906.72, 43892.6, 43901.01, 21.14603],
 [1703196240000, 43901.01, 43944.91, 43901.0, 43944.91, 27.15943],
 [1703196300000, 43944.91, 43988.78, 43931.1, 43972.16, 20.74029],
 [1703196360000, 43972.15, 43997.85, 43972.15, 43997.78, 11.05708],
 [1703196420000, 43997.79, 43997.79, 43983.22, 43986.47, 8.49329],
 [1703196480000, 43986.48, 43986.48, 43972.16, 43976.13, 11.2228],
 [1703196540000, 43976.13, 44006.98, 43976.13, 43980.35, 17.90783],
 [1703196600000, 43980.35, 43991.09, 43980.35, 43983.48, 8.47253],
 [1703196660000, 43983.48, 44006.12, 43983.47, 44006.09, 10.02965],
 [1703196720000, 44006.09, 44020.4, 43989.7, 43989.71, 27.09781],
 [1703196780000, 43989.7, 43989.71, 43964.2, 43965.96, 11.54396],
 [1703196840000, 43965.95, 43965.96, 43956.65, 43956.66, 9.15914],
 [1703196900000, 43956.66, 43956.66, 43923.0, 43923.01, 37.08148],
 [1703196960000, 43923.01, 43938.5, 43923.0, 43933.05, 9.34491],
 [1703197020000, 43933.04, 43948.32, 43933.04, 43939.18, 19.19603],
 [1703197080000, 43939.19, 43980.32, 43939.18, 43980.22, 13.48489],
 [1703197140000, 43980.21, 43987.06, 43980.21, 43983.5, 12.52761],
 [1703197200000, 43983.5, 43983.51, 43971.1, 43971.11, 8.48999],
 [1703197260000, 43971.1, 43987.64, 43971.1, 43987.63, 15.84852],
 [1703197320000, 43987.63, 43987.64, 43964.15, 43964.15, 12.99581],
 [1703197380000, 43964.15, 43987.64, 43953.34, 43986.8, 21.39369],
 [1703197440000, 43986.81, 43986.81, 43982.76, 43982.76, 6.91437],
 [1703197500000, 43982.77, 43986.0, 43982.76, 43985.99, 8.08299],
 [1703197560000, 43985.99, 43989.83, 43982.76, 43989.83, 10.34569],
 [1703197620000, 43989.82, 43989.83, 43989.61, 43989.62, 5.42836],
 [1703197680000, 43989.61, 43999.0, 43989.61, 43998.99, 6.32304],
 [1703197740000, 43999.0, 43999.0, 43989.61, 43989.62, 8.20692],
 [1703197800000, 43989.61, 43989.62, 43905.48, 43905.49, 19.12926],
 [1703197860000, 43905.48, 43905.49, 43885.53, 43886.86, 18.53636],
 [1703197920000, 43886.86, 43960.37, 43886.85, 43960.37, 14.22807],
 [1703197980000, 43960.36, 43960.37, 43929.5, 43929.5, 13.12772],
 [1703198040000, 43929.5, 43929.51, 43896.45, 43920.44, 16.83313],
 [1703198100000, 43920.44, 43920.44, 43902.87, 43913.09, 10.07992],
 [1703198160000, 43913.08, 43954.2, 43913.08, 43953.32, 9.67124],
 [1703198220000, 43953.33, 43954.09, 43929.85, 43929.85, 6.7642],
 [1703198280000, 43929.85, 43956.71, 43927.76, 43956.71, 17.24019],
 [1703198340000, 43956.7, 43980.87, 43956.7, 43976.99, 13.32775],
 [1703198400000, 43976.99, 43980.87, 43976.99, 43980.86, 7.64294],
 [1703198460000, 43980.86, 43980.87, 43954.62, 43954.62, 5.70295],
 [1703198520000, 43954.62, 43954.63, 43927.83, 43927.84, 9.03048],
 [1703198580000, 43927.83, 43927.84, 43923.16, 43923.16, 7.4119],
 [1703198640000, 43923.17, 43980.86, 43923.16, 43980.85, 20.87965],
 [1703198700000, 43980.85, 43981.1, 43980.85, 43981.09, 9.10703],
 [1703198760000, 43981.09, 43981.1, 43981.09, 43981.09, 3.58022],
 [1703198820000, 43981.1, 43981.1, 43981.09, 43981.1, 9.94141],
 [1703198880000, 43981.09, 43996.77, 43981.09, 43996.77, 17.37328],
 [1703198940000, 43996.76, 43996.87, 43996.76, 43996.87, 7.88786],
 [1703199000000, 43996.86, 43996.87, 43993.12, 43993.12, 9.52418],
 [1703199060000, 43993.12, 43993.13, 43946.34, 43946.35, 17.63763],
 [1703199120000, 43946.35, 43946.35, 43915.63, 43915.63, 7.10687],
 [1703199180000, 43915.64, 43946.32, 43915.63, 43946.32, 13.11142],
 [1703199240000, 43946.31, 43949.93, 43946.31, 43949.93, 11.87476],
 [1703199300000, 43949.92, 43949.93, 43949.92, 43949.93, 3.54644],
 [1703199360000, 43949.92, 43949.93, 43933.09, 43933.1, 9.51394],
 [1703199420000, 43933.09, 43944.61, 43927.54, 43944.61, 10.39856],
 [1703199480000, 43944.61, 43949.68, 43944.6, 43949.67, 5.79413],
 [1703199540000, 43949.67, 43949.68, 43949.43, 43949.44, 4.34638],
 [1703199600000, 43949.43, 43950.0, 43932.42, 43932.42, 25.50086],
 [1703199660000, 43932.43, 43947.08, 43932.42, 43947.07, 5.08847],
 [1703199720000, 43947.07, 43947.08, 43901.48, 43901.48, 22.54996],
 [1703199780000, 43901.48, 43911.35, 43901.48, 43901.59, 11.53266],
 [1703199840000, 43901.59, 43912.76, 43900.0, 43909.99, 18.14716],
 [1703199900000, 43910.0, 43910.0, 43881.24, 43886.0, 18.19358],
 [1703199960000, 43886.0, 43889.94, 43881.26, 43881.94, 16.72891],
 [1703200020000, 43881.93, 43907.78, 43881.93, 43884.39, 12.25068],
 [1703200080000, 43884.39, 43884.4, 43861.86, 43861.87, 28.10756],
 [1703200140000, 43861.87, 43892.04, 43861.86, 43892.04, 31.93844],
 [1703200200000, 43892.03, 43938.0, 43892.03, 43929.67, 24.05019],
 [1703200260000, 43929.66, 43941.06, 43921.1, 43941.05, 16.18662],
 [1703200320000, 43941.05, 43942.14, 43930.41, 43937.25, 12.42714],
 [1703200380000, 43937.25, 43937.25, 43918.22, 43918.23, 11.03008],
 [1703200440000, 43918.22, 43918.23, 43888.91, 43900.54, 18.51841],
 [1703200500000, 43900.55, 43928.1, 43900.54, 43924.13, 15.0926],
 [1703200560000, 43924.12, 43924.13, 43891.99, 43907.51, 15.09269],
 [1703200620000, 43907.5, 43910.95, 43900.01, 43906.4, 9.8331],
 [1703200680000, 43906.41, 43906.41, 43886.0, 43895.0, 5.40658],
 [1703200740000, 43895.0, 43895.0, 43884.0, 43884.16, 9.39901],
 [1703200800000, 43884.17, 43893.08, 43882.01, 43882.01, 16.73544],
 [1703200860000, 43882.01, 43882.02, 43862.01, 43867.92, 17.24984],
 [1703200920000, 43867.93, 43881.57, 43863.88, 43881.56, 11.783],
 [1703200980000, 43881.57, 43881.57, 43871.1, 43871.1, 6.85805],
 [1703201040000, 43871.1, 43890.65, 43871.1, 43888.46, 15.7121],
 [1703201100000, 43888.46, 43900.0, 43888.45, 43899.99, 7.87147],
 [1703201160000, 43900.0, 43900.0, 43892.29, 43900.0, 8.64091],
 [1703201220000, 43899.99, 43900.45, 43899.99, 43900.45, 5.00696],
 [1703201280000, 43900.45, 43901.0, 43889.11, 43889.12, 9.95661],
 [1703201340000, 43889.12, 43900.86, 43889.11, 43900.86, 3.55841],
 [1703201400000, 43900.86, 43913.87, 43900.85, 43905.75, 10.29693],
 [1703201460000, 43905.74, 43905.75, 43867.78, 43867.78, 12.26074],
 [1703201520000, 43867.79, 43867.79, 43842.5, 43847.07, 22.43254],
 [1703201580000, 43847.06, 43849.65, 43838.52, 43849.65, 8.55912],
 [1703201640000, 43849.65, 43860.0, 43849.64, 43860.0, 5.40517],
 [1703201700000, 43860.0, 43862.85, 43849.65, 43855.99, 11.08736],
 [1703201760000, 43855.99, 43856.0, 43851.84, 43855.29, 4.18181],
 [1703201820000, 43855.29, 43855.29, 43823.52, 43823.53, 12.0986],
 [1703201880000, 43823.53, 43833.45, 43810.6, 43827.99, 27.40782],
 [1703201940000, 43827.99, 43828.0, 43820.11, 43820.11, 14.90211],
 [1703202000000, 43820.12, 43825.52, 43820.1, 43820.99, 12.59986],
 [1703202060000, 43820.99, 43840.0, 43820.98, 43839.99, 13.11733],
 [1703202120000, 43840.0, 43840.0, 43835.93, 43835.93, 9.07842],
 [1703202180000, 43835.93, 43835.99, 43835.93, 43835.98, 3.86062],
 [1703202240000, 43835.98, 43835.99, 43835.98, 43835.98, 9.34835],
 [1703202300000, 43835.98, 43835.99, 43797.0, 43797.01, 25.01961],
 [1703202360000, 43797.0, 43811.1, 43793.34, 43806.77, 11.04065],
 [1703202420000, 43806.77, 43835.99, 43806.77, 43834.92, 18.50387],
 [1703202480000, 43834.93, 43834.93, 43830.94, 43830.94, 8.16772],
 [1703202540000, 43830.95, 43839.45, 43823.0, 43836.58, 11.87574],
 [1703202600000, 43836.57, 43838.14, 43826.18, 43838.14, 5.58143],
 [1703202660000, 43838.14, 43840.0, 43838.13, 43839.99, 3.26685],
 [1703202720000, 43840.0, 43849.4, 43839.99, 43849.4, 9.37332],
 [1703202780000, 43849.4, 43849.4, 43841.07, 43843.92, 5.67279],
 [1703202840000, 43843.92, 43849.4, 43839.99, 43849.4, 6.21628],
 [1703202900000, 43849.4, 43871.05, 43849.39, 43871.04, 35.96115],
 [1703202960000, 43871.04, 43871.05, 43861.02, 43861.02, 13.60862],
 [1703203020000, 43861.03, 43865.31, 43860.0, 43861.8, 10.93191],
 [1703203080000, 43861.79, 43861.8, 43861.79, 43861.79, 4.44978],
 [1703203140000, 43861.79, 43861.8, 43861.79, 43861.8, 3.66335],
 [1703203200000, 43861.79, 43861.8, 43861.79, 43861.79, 7.85091],
 [1703203260000, 43861.79, 43870.57, 43861.79, 43863.05, 10.77632],
 [1703203320000, 43863.05, 43867.03, 43855.31, 43858.01, 13.27892],
 [1703203380000, 43858.0, 43858.01, 43846.0, 43846.0, 10.24839],
 [1703203440000, 43846.0, 43846.01, 43827.38, 43827.39, 6.77618],
 [1703203500000, 43827.38, 43827.39, 43799.81, 43804.96, 37.28765],
 [1703203560000, 43804.96, 43804.96, 43799.76, 43801.97, 11.82455],
 [1703203620000, 43801.98, 43806.8, 43783.92, 43783.93, 14.26648],
 [1703203680000, 43783.92, 43800.0, 43783.92, 43799.99, 5.22272],
 [1703203740000, 43799.99, 43809.99, 43799.99, 43809.99, 9.81656],
 [1703203800000, 43809.99, 43809.99, 43784.52, 43790.75, 13.71357],
 [1703203860000, 43790.75, 43796.54, 43785.88, 43785.89, 8.9235],
 [1703203920000, 43785.89, 43796.8, 43785.88, 43796.8, 8.57357],
 [1703203980000, 43796.79, 43796.8, 43795.21, 43795.22, 4.88868],
 [1703204040000, 43795.22, 43795.22, 43790.0, 43790.0, 5.93868],
 [1703204100000, 43790.0, 43798.94, 43780.0, 43780.01, 13.04815],
 [1703204160000, 43780.0, 43780.01, 43775.0, 43775.01, 9.70762],
 [1703204220000, 43775.0, 43813.18, 43722.46, 43813.17, 57.70903],
 [1703204280000, 43813.17, 43837.45, 43810.82, 43837.45, 18.55932],
 [1703204340000, 43837.44, 43856.59, 43837.44, 43856.59, 14.21057],
 [1703204400000, 43856.58, 43857.6, 43852.55, 43853.01, 19.08433],
 [1703204460000, 43853.01, 43879.96, 43853.0, 43871.04, 9.98973],
 [1703204520000, 43871.03, 43878.37, 43869.03, 43869.03, 7.15125],
 [1703204580000, 43869.04, 43881.65, 43869.03, 43881.65, 7.04235],
 [1703204640000, 43881.65, 43883.72, 43878.37, 43883.72, 7.83549],
 [1703204700000, 43883.72, 43883.72, 43873.16, 43873.17, 7.53566],
 [1703204760000, 43873.16, 43895.8, 43873.16, 43874.52, 20.85687],
 [1703204820000, 43874.51, 43887.8, 43874.51, 43885.56, 5.00422],
 [1703204880000, 43885.56, 43922.8, 43885.56, 43922.79, 23.52096],

In [12]:
df

,date,open,high,low,close,volume,Code
0,2023-12-01 00:00:00+00:00,37723.97,37744.72,37722.73,37738.91,34.53633,BTCUSDT
1,2023-12-01 00:01:00+00:00,37738.91,37738.91,37723.72,37723.72,12.71120,BTCUSDT
2,2023-12-01 00:02:00+00:00,37723.72,37723.73,37699.57,37699.57,33.22694,BTCUSDT
3,2023-12-01 00:03:00+00:00,37699.58,37699.58,37699.57,37699.57,6.89939,BTCUSDT
4,2023-12-01 00:04:00+00:00,37699.57,37699.58,37688.27,37688.35,14.22495,BTCUSDT
...,...,...,...,...,...,...,...
30535,2023-12-22 04:25:00+00:00,44045.24,44077.86,44045.23,44069.94,27.70364,BTCUSDT
30536,2023-12-22 04:26:00+00:00,44069.95,44079.65,44061.10,44074.01,18.59401,BTCUSDT
30537,2023-12-22 04:27:00+00:00,44074.01,44074.01,44062.00,44066.82,12.53198,BTCUSDT
30538,2023-12-22 04:28:00+00:00,44066.81,44075.00,44062.14,44075.00,10.50742,BTCUSDT
30539,2023-12-22 04:29:00+00:00,44074.99,44075.00,44070.03,44070.04,5.81998,BTCUSDT

# tail